export const BRAZILIAN_BANKS = [
    { code: "260", name: "Nubank" },
    { code: "077", name: "Inter" },
    { code: "341", name: "Itaú Unibanco" },
    { code: "001", name: "Banco do Brasil" },
    { code: "237", name: "Bradesco" },
    { code: "104", name: "Caixa Econômica Federal" },
    { code: "033", name: "Santander" },
    { code: "290", name: "PagBank" },
    { code: "380", name: "PicPay" },
    { code: "323", name: "Mercado Pago" },
    { code: "070", name: "BRB - Banco de Brasília" },
    { code: "655", name: "Banco Votorantim (Neon)" },
    { code: "336", name: "C6 Bank" },
    { code: "212", name: "Banco Original" },
    { code: "041", name: "Banrisul" },
    { code: "021", name: "Banestes" },
    { code: "756", name: "Sicoob" },
    { code: "748", name: "Sicredi" },
    { code: "047", name: "Banese" },
    { code: "197", name: "Stone" },
    { code: "654", name: "Banco Digio" },
    { code: "079", name: "Banco Original" },
    { code: "218", name: "Banco BS2" },
    { code: "637", name: "Banco Sofisa" },
    { code: "069", name: "Crefisa" },
    { code: "318", name: "Banco BMG" },
    { code: "633", name: "Banco Rendimento" },
    { code: "208", name: "Banco BTG Pactual" },
    { code: "246", name: "Banco ABC Brasil" },
    { code: "755", name: "Bank of America Merrill Lynch" },
    { code: "025", name: "Banco Alfa" },
    { code: "641", name: "Banco Alvorada" },
    { code: "029", name: "Banco Banerj" },
    { code: "000", name: "Banco Bankpar" },
    { code: "740", name: "Banco Barclays" },
    { code: "107", name: "Banco BBM" },
    { code: "031", name: "Banco Beg" },
    { code: "096", name: "Banco BM&F" },
    { code: "218", name: "Banco Bonsucesso" },
    { code: "036", name: "Banco Bradesco BBI" },
    { code: "204", name: "Banco Bradesco Cartões" },
    { code: "633", name: "Banco Rendimento" },
    { code: "320", name: "Banco Industrial e Comercial" },
].sort((a, b) => a.name.localeCompare(b.name));
